In [1]:
import os
import pandas as pd

In [2]:
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

In [8]:
blogs = BlogPage.objects.all()

In [9]:
blogs_df = pd.DataFrame(list(BlogPage.objects.all().values()))

In [10]:
blogs_df

,body,content_type_id,cover_id,date,depth,draft_title,expire_at,expired,first_published_at,go_live_at,...,numchild,owner_id,page_ptr_id,path,search_description,seo_title,show_in_menus,slug,title,url_path
0,<p>Blog-1 Body</p>,98,1.0,2020-06-23,3,Blog-1,None,False,2020-06-23 12:39:04.297379+00:00,None,...,0,1,6,000100010001,,,False,blog-1,Blog-1,/blog/blog-1/
1,<p>Blog-2 Body</p>,98,NaN,2020-06-09,3,Blog-2,None,False,2020-06-23 12:39:33.388216+00:00,None,...,0,1,7,000100010002,,,False,blog-2,Blog-2,/blog/blog-2/
2,<p>Newest Blog Post Body</p>,98,2.0,2020-06-24,3,Newest Blog Post,None,False,2020-06-23 12:39:58.599398+00:00,None,...,0,1,8,000100010003,,,False,newest-blog-post,Newest Blog Post,/blog/newest-blog-post/
3,<p>Oldegst Blog Post Body</p>,98,NaN,2020-06-02,3,Oldest Blog Post,None,False,2020-06-23 12:40:24.358112+00:00,None,...,0,1,9,000100010004,,,False,oldest-blog-post,Oldest Blog Post,/blog/oldest-blog-post/
4,<p>dfher</p>,98,NaN,2020-06-12,3,Some other blog post,None,False,2020-06-23 14:09:09.725852+00:00,None,...,0,1,10,000100010005,,,False,some-other-blog-post,Some other blog post,/blog/some-other-blog-post/

In [24]:
def payment_plan(amount, maturity, interest, bsmv, kkdf):
    total_interest = interest + interest * kkdf + interest * bsmv
    monthly_payment = (total_interest * amount) / (1 - (1 + total_interest) ** (-1 * maturity))
    payment_plan = pd.DataFrame(index=range(maturity), columns=['month','monthly_pay','principal_before','principal_paid','interest_paid','kkdf','bsmv','principal_left'])

    for i in range(maturity):
        if i == 0:
            principal_before = amount
        else:
            principal_before = payment_plan.loc[i-1, 'principal_left']

        interest_paid = principal_before * interest
        kkdf_paid = interest_paid * kkdf
        bsmv_paid = interest_paid * bsmv
        principal_paid = monthly_payment - interest_paid - kkdf_paid - bsmv_paid
        principal_left = principal_before - principal_paid

        payment_plan.loc[i] = [i+1,monthly_payment, principal_before, principal_paid, interest_paid, kkdf_paid, bsmv_paid, principal_left]
        payment_plan = payment_plan.astype('float')

    payment_plan.drop('principal_before', axis=1, inplace=True)
    payment_plan = payment_plan.round(0)
    payment_plan.iloc[-1,-1]=0
    # Format cells
    payment_plan['month']=payment_plan['month'].astype(int)
    
    payment_plan.columns=['Ay','Taksit','Anapara','Faiz','KKDF','BSMV','Kalan Ã–deme']
    return payment_plan

In [25]:
df = payment_plan(30000,30,0.003,0.005,0.005)

In [27]:
df['Taksit'].map('{:,.2f} â‚º'.format)

0     $1,048.00
1     $1,048.00
2     $1,048.00
3     $1,048.00
4     $1,048.00
5     $1,048.00
6     $1,048.00
7     $1,048.00
8     $1,048.00
9     $1,048.00
10    $1,048.00
11    $1,048.00
12    $1,048.00
13    $1,048.00
14    $1,048.00
15    $1,048.00
16    $1,048.00
17    $1,048.00
18    $1,048.00
19    $1,048.00
20    $1,048.00
21    $1,048.00
22    $1,048.00
23    $1,048.00
24    $1,048.00
25    $1,048.00
26    $1,048.00
27    $1,048.00
28    $1,048.00
29    $1,048.00
Name: Taksit, dtype: object

In [12]:
for i, j in df.iterrows():
    print("i: "+str(i))
    print("j: "+str(j['monthly_pay']))
    print("----")

i: 0
j: 1048.0
----
i: 1
j: 1048.0
----
i: 2
j: 1048.0
----
i: 3
j: 1048.0
----
i: 4
j: 1048.0
----
i: 5
j: 1048.0
----
i: 6
j: 1048.0
----
i: 7
j: 1048.0
----
i: 8
j: 1048.0
----
i: 9
j: 1048.0
----
i: 10
j: 1048.0
----
i: 11
j: 1048.0
----
i: 12
j: 1048.0
----
i: 13
j: 1048.0
----
i: 14
j: 1048.0
----
i: 15
j: 1048.0
----
i: 16
j: 1048.0
----
i: 17
j: 1048.0
----
i: 18
j: 1048.0
----
i: 19
j: 1048.0
----
i: 20
j: 1048.0
----
i: 21
j: 1048.0
----
i: 22
j: 1048.0
----
i: 23
j: 1048.0
----
i: 24
j: 1048.0
----
i: 25
j: 1048.0
----
i: 26
j: 1048.0
----
i: 27
j: 1048.0
----
i: 28
j: 1048.0
----
i: 29
j: 1048.0
----